// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChlaIsTZxAYhuqnQCOpSjwpEfoSDknWb8',
    appId: '1:224198280580:web:36858b07d77015cb69c9d1',
    messagingSenderId: '224198280580',
    projectId: 'cinemaappticket',
    authDomain: 'cinemaappticket.firebaseapp.com',
    databaseURL: 'https://cinemaappticket-default-rtdb.firebaseio.com',
    storageBucket: 'cinemaappticket.appspot.com',
    measurementId: 'G-CMD5ZQGP6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6lYpa8zWIwaNI2GAw0sPPOZkpGhLgEW4',
    appId: '1:224198280580:android:f0c3a6a22a966cc969c9d1',
    messagingSenderId: '224198280580',
    projectId: 'cinemaappticket',
    databaseURL: 'https://cinemaappticket-default-rtdb.firebaseio.com',
    storageBucket: 'cinemaappticket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA94l7Qz5h3i0UjPQrePeHTDv5_cgiVsB4',
    appId: '1:224198280580:ios:5406c048ad241feb69c9d1',
    messagingSenderId: '224198280580',
    projectId: 'cinemaappticket',
    databaseURL: 'https://cinemaappticket-default-rtdb.firebaseio.com',
    storageBucket: 'cinemaappticket.appspot.com',
    iosBundleId: 'com.example.libercopiaBookstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA94l7Qz5h3i0UjPQrePeHTDv5_cgiVsB4',
    appId: '1:224198280580:ios:5406c048ad241feb69c9d1',
    messagingSenderId: '224198280580',
    projectId: 'cinemaappticket',
    databaseURL: 'https://cinemaappticket-default-rtdb.firebaseio.com',
    storageBucket: 'cinemaappticket.appspot.com',
    iosBundleId: 'com.example.libercopiaBookstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChlaIsTZxAYhuqnQCOpSjwpEfoSDknWb8',
    appId: '1:224198280580:web:31ef4757c3db420569c9d1',
    messagingSenderId: '224198280580',
    projectId: 'cinemaappticket',
    authDomain: 'cinemaappticket.firebaseapp.com',
    databaseURL: 'https://cinemaappticket-default-rtdb.firebaseio.com',
    storageBucket: 'cinemaappticket.appspot.com',
    measurementId: 'G-BSCRWX2FQZ',
  );

}