import 'package:libercopia_bookstore_app/utils/constants/image_strings.dart';

import '../../data/models/author_model.dart';
import '../../data/models/book_model.dart';
import '../../data/models/category_model.dart';

class LDummyBooks {
  static final List<BookModel> books = [
    BookModel(
      id: '1',
      title: 'Harry Potter and the Philosopher\'s Stone',
      description: 'The first book in the Harry Potter series',
      isbn: '9780747532743',
      price: 19.99,
      stock: 100,
      author: AuthorModel(
        // ✅ Replaced authorId with full AuthorModel
        id: '1',
        name: 'J.K. Rowling',
        bio: 'British author, best known for Harry Potter series.',
        photoUrl: LImages.user,
        createdAt: DateTime.now(),
      ),
      category: CategoryModel(
        id: '11',
        name: 'Fantasy',
        image: LImages.user,
        isFeatured: true,
        parentId: '1',
        createdAt: DateTime.now(),
      ),
      imageUrls: [LImages.bookCover1],
      publishedDate: DateTime(1997, 6, 26),
      publisher: 'Bloomsbury',
      language: 'English',
      pages: 223,
      rating: 4.8,
      reviewsCount: 1250,
      createdAt: DateTime.now(),
      isFeatured: true,
    ),
    BookModel(
      id: '2',
      title: 'Harry Potter and the Chamber of Secrets',
      description: 'The second book in the Harry Potter series',
      isbn: '9780747538493',
      price: 21.99,
      stock: 85,
      author: AuthorModel(
        id: '1',
        name: 'J.K. Rowling',
        bio: 'British author, best known for Harry Potter series.',
        createdAt: DateTime.now(),
        photoUrl: LImages.user,
      ),
      category: CategoryModel(
        id: '11',
        name: 'Fantasy',
        image: LImages.user,
        isFeatured: true,
        parentId: '1',
        createdAt: DateTime.now(),
      ),
      imageUrls: [LImages.bookCover2],
      publishedDate: DateTime(1998, 7, 2),
      publisher: 'Bloomsbury',
      language: 'English',
      pages: 251,
      rating: 4.7,
      reviewsCount: 980,
      createdAt: DateTime.now(),
      isFeatured: false,
    ),
    BookModel(
      id: '3',
      title: 'The Shining',
      description: 'A psychological horror novel',
      isbn: '9780307743657',
      price: 15.99,
      stock: 75,
      author: AuthorModel(
        id: '2',
        name: 'Stephen King',
        bio: 'American author, known for horror novels.',
        createdAt: DateTime.now(),
        photoUrl: LImages.user,
      ),
      category: CategoryModel(
        id: '11',
        name: 'Fantasy',
        image: LImages.user,
        isFeatured: true,
        parentId: '1',
        createdAt: DateTime.now(),
      ),
      imageUrls: [LImages.bookCover3],
      publishedDate: DateTime(1977, 1, 28),
      publisher: 'Doubleday',
      language: 'English',
      pages: 447,
      rating: 4.6,
      reviewsCount: 1345,
      createdAt: DateTime.now(),
      isFeatured: true,
    ),
    BookModel(
      id: '4',
      title: 'IT',
      description: 'Epic horror novel about an evil clown',
      isbn: '9781501142970',
      price: 24.99,
      stock: 60,
      author: AuthorModel(
        id: '2',
        name: 'Stephen King',
        bio: 'American author, known for horror novels.',
        createdAt: DateTime.now(),
        photoUrl: LImages.user,
      ),
      category: CategoryModel(
        id: '11',
        name: 'Fantasy',
        image: LImages.user,
        isFeatured: true,
        parentId: '1',
        createdAt: DateTime.now(),
      ),
      imageUrls: [LImages.bookCover4],
      publishedDate: DateTime(1986, 9, 15),
      publisher: 'Viking',
      language: 'English',
      pages: 1138,
      rating: 4.5,
      reviewsCount: 1620,
      createdAt: DateTime.now(),
      isFeatured: false,
    ),
  ];
}
